name: btr_gov
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  http: ^0.13.3
  provider: ^6.0.0
  fluttertoast: ^8.2.8
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_picker: ^0.8.7+4
  json_serializable: ^6.1.5
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.11.0  # Add this here for launcher icon generation

flutter:
  uses-material-design: true

  assets:
    - resources/image/BTRgov-logo.png
    - assets/images/dashoard.svg
    - assets/images/account.svg
    - assets/images/add_famer.svg
    - assets/images/address_inf.svg
    - assets/images/arow_right_canva.svg
    - assets/images/assets.svg
    - assets/images/back_arrow.svg
    - assets/images/create_icom_fermer.svg
    - assets/images/delete.svg
    - assets/images/edit.svg
    - assets/images/family_detials.svg
    - assets/images/farmer.svg
    - assets/images/file_breacrum.svg
    - assets/images/header_member.svg
    - assets/images/location.svg
    - assets/images/message.svg
    - assets/images/passbook.svg
    - assets/images/personal_detials.svg
    - assets/images/photo_upload.svg
    - assets/images/ragistor_view.svg
    - assets/images/socail_info.svg
    - assets/images/sreach.svg
    - assets/images/status.svg
    - assets/images/upload.svg
    - assets/images/app_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
